# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import logging
logger = logging.getLogger()
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        logger.debug('set up UI')
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1412, 894)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_14.addWidget(self.add_btn)
        self.combo_add = QtWidgets.QComboBox(self.centralwidget)
        self.combo_add.setObjectName("combo_add")
        self.combo_add.addItem("")
        self.combo_add.addItem("")
        self.horizontalLayout_14.addWidget(self.combo_add)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.combo_img1 = QtWidgets.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.combo_img1.setFont(font)
        self.combo_img1.setObjectName("combo_img1")
        self.combo_img1.addItem("")
        self.combo_img1.addItem("")
        self.combo_img1.addItem("")
        self.combo_img1.addItem("")
        self.horizontalLayout_5.addWidget(self.combo_img1)
        spacerItem2 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gView_img1 = PlotWidget(self.frame)
        self.gView_img1.setObjectName("gView_img1")
        self.horizontalLayout_6.addWidget(self.gView_img1)
        spacerItem3 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gView_trans1 = PlotWidget(self.frame)
        self.gView_trans1.setObjectName("gView_trans1")
        self.horizontalLayout_6.addWidget(self.gView_trans1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.combo_img2 = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.combo_img2.setFont(font)
        self.combo_img2.setObjectName("combo_img2")
        self.combo_img2.addItem("")
        self.combo_img2.addItem("")
        self.combo_img2.addItem("")
        self.combo_img2.addItem("")
        self.horizontalLayout_3.addWidget(self.combo_img2)
        spacerItem5 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gView_img2 = PlotWidget(self.frame_2)
        self.gView_img2.setObjectName("gView_img2")
        self.horizontalLayout_4.addWidget(self.gView_img2)
        spacerItem6 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.gView_trans2 = PlotWidget(self.frame_2)
        self.gView_trans2.setObjectName("gView_trans2")
        self.horizontalLayout_4.addWidget(self.gView_trans2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_10.addWidget(self.frame_2)
        self.horizontalLayout_15.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        spacerItem7 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.combo_mix = QtWidgets.QComboBox(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.combo_mix.setFont(font)
        self.combo_mix.setObjectName("combo_mix")
        self.combo_mix.addItem("")
        self.combo_mix.addItem("")
        self.horizontalLayout_2.addWidget(self.combo_mix)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.combo_comp1_img = QtWidgets.QComboBox(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.combo_comp1_img.setFont(font)
        self.combo_comp1_img.setObjectName("combo_comp1_img")
        self.combo_comp1_img.addItem("")
        self.combo_comp1_img.addItem("")
        self.horizontalLayout_11.addWidget(self.combo_comp1_img)
        self.combo_comp1 = QtWidgets.QComboBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_comp1.sizePolicy().hasHeightForWidth())
        self.combo_comp1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.combo_comp1.setFont(font)
        self.combo_comp1.setObjectName("combo_comp1")
        self.combo_comp1.addItem("")
        self.combo_comp1.addItem("")
        self.combo_comp1.addItem("")
        self.combo_comp1.addItem("")
        self.horizontalLayout_11.addWidget(self.combo_comp1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem10 = QtWidgets.QSpacerItem(210, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem10)
        self.comp1_uniform = QtWidgets.QCheckBox(self.frame_3)
        self.comp1_uniform.setObjectName("comp1_uniform")
        self.horizontalLayout_16.addWidget(self.comp1_uniform)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        spacerItem11 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        spacerItem12 = QtWidgets.QSpacerItem(230, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.slider_comp1 = QtWidgets.QSlider(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_comp1.sizePolicy().hasHeightForWidth())
        self.slider_comp1.setSizePolicy(sizePolicy)
        self.slider_comp1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_comp1.setObjectName("slider_comp1")
        self.verticalLayout_6.addWidget(self.slider_comp1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem13)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.slider_val1 = QtWidgets.QTextBrowser(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_val1.sizePolicy().hasHeightForWidth())
        self.slider_val1.setSizePolicy(sizePolicy)
        self.slider_val1.setMaximumSize(QtCore.QSize(41, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.slider_val1.setFont(font)
        self.slider_val1.setObjectName("slider_val1")
        self.verticalLayout_15.addWidget(self.slider_val1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_15.addItem(spacerItem14)
        self.horizontalLayout.addLayout(self.verticalLayout_15)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.combo_comp2_img = QtWidgets.QComboBox(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.combo_comp2_img.setFont(font)
        self.combo_comp2_img.setObjectName("combo_comp2_img")
        self.combo_comp2_img.addItem("")
        self.combo_comp2_img.addItem("")
        self.horizontalLayout_12.addWidget(self.combo_comp2_img)
        self.combo_comp2 = QtWidgets.QComboBox(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.combo_comp2.setFont(font)
        self.combo_comp2.setObjectName("combo_comp2")
        self.combo_comp2.addItem("")
        self.combo_comp2.addItem("")
        self.combo_comp2.addItem("")
        self.combo_comp2.addItem("")
        self.horizontalLayout_12.addWidget(self.combo_comp2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem15 = QtWidgets.QSpacerItem(210, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem15)
        self.comp2_uniform = QtWidgets.QCheckBox(self.frame_3)
        self.comp2_uniform.setObjectName("comp2_uniform")
        self.horizontalLayout_17.addWidget(self.comp2_uniform)
        self.verticalLayout_14.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        spacerItem16 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem16)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        spacerItem17 = QtWidgets.QSpacerItem(230, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem17)
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.slider_comp2 = QtWidgets.QSlider(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_comp2.sizePolicy().hasHeightForWidth())
        self.slider_comp2.setSizePolicy(sizePolicy)
        self.slider_comp2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_comp2.setObjectName("slider_comp2")
        self.verticalLayout_7.addWidget(self.slider_comp2)
        spacerItem18 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem18)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.slider_val2 = QtWidgets.QTextBrowser(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_val2.sizePolicy().hasHeightForWidth())
        self.slider_val2.setSizePolicy(sizePolicy)
        self.slider_val2.setMaximumSize(QtCore.QSize(41, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.slider_val2.setFont(font)
        self.slider_val2.setObjectName("slider_val2")
        self.verticalLayout_17.addWidget(self.slider_val2)
        spacerItem19 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_17.addItem(spacerItem19)
        self.horizontalLayout_10.addLayout(self.verticalLayout_17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_11.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        spacerItem20 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.gView_output1 = PlotWidget(self.frame_4)
        self.gView_output1.setObjectName("gView_output1")
        self.horizontalLayout_7.addWidget(self.gView_output1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        spacerItem21 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem21)
        self.gView_output2 = PlotWidget(self.frame_4)
        self.gView_output2.setObjectName("gView_output2")
        self.horizontalLayout_8.addWidget(self.gView_output2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout_11.addWidget(self.frame_4)
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1412, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_btn.setText(_translate("MainWindow", "Add Image"))
        self.combo_add.setItemText(0, _translate("MainWindow", "Image1"))
        self.combo_add.setItemText(1, _translate("MainWindow", "Image2"))
        self.label.setText(_translate("MainWindow", "Image1"))
        self.combo_img1.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.combo_img1.setItemText(1, _translate("MainWindow", "Phase"))
        self.combo_img1.setItemText(2, _translate("MainWindow", "Real"))
        self.combo_img1.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.label_3.setText(_translate("MainWindow", "Image2"))
        self.combo_img2.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.combo_img2.setItemText(1, _translate("MainWindow", "Phase"))
        self.combo_img2.setItemText(2, _translate("MainWindow", "Real"))
        self.combo_img2.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.label_11.setText(_translate("MainWindow", " Mixer OutPut to:"))
        self.combo_mix.setItemText(0, _translate("MainWindow", "OutPut1"))
        self.combo_mix.setItemText(1, _translate("MainWindow", "OutPut2"))
        self.label_5.setText(_translate("MainWindow", "Component1:"))
        self.combo_comp1_img.setItemText(0, _translate("MainWindow", "Image1"))
        self.combo_comp1_img.setItemText(1, _translate("MainWindow", "Image2"))
        self.combo_comp1.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.combo_comp1.setItemText(1, _translate("MainWindow", "Phase"))
        self.combo_comp1.setItemText(2, _translate("MainWindow", "Real"))
        self.combo_comp1.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.comp1_uniform.setText(_translate("MainWindow", "Uniform"))
        self.label_13.setText(_translate("MainWindow", "0%"))
        self.label_14.setText(_translate("MainWindow", "100%"))
        self.slider_val1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Component2:"))
        self.combo_comp2_img.setItemText(0, _translate("MainWindow", "Image1"))
        self.combo_comp2_img.setItemText(1, _translate("MainWindow", "Image2"))
        self.combo_comp2.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.combo_comp2.setItemText(1, _translate("MainWindow", "Phase"))
        self.combo_comp2.setItemText(2, _translate("MainWindow", "Real"))
        self.combo_comp2.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.comp2_uniform.setText(_translate("MainWindow", "Uniform"))
        self.label_15.setText(_translate("MainWindow", "0%"))
        self.label_16.setText(_translate("MainWindow", "100%"))
        self.slider_val2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "OutPut1"))
        self.label_12.setText(_translate("MainWindow", "OutPut2"))
from pyqtgraph import PlotWidget
